### ISSUE TITLE
How to run restrainingorder on specific chromosome as it is running currently for Chromosome1 

### ISSUE THREAD

**Issue by luckysardar** [FelixKrueger/reStrainingOrder#3]
Hello felix 

Once again Thank you for the wonderfull tool and idea I just wonder is is possible run it on specific chromosome like X and Y it will very helpfull I tried but I am newbee to perl scripts 

Thank you

**Comment by luckysardar** [comment]
Any comment on my issue please help

**Comment by FelixKrueger** [comment]
Hi there, I am so sorry but I just can't seem to find the time to look at this currently. I do have one comment, and one question nevertheless. 

As a comment, the Y chromosome is notoriously difficult to work with as it mostly consists of repetitive sequences. Here is a quote I found in [this publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2435358/#:~:text=The%20pseudoautosomal%20regions%20(PAR1%20and%20PAR2)%20are%20short%20regions%20of,a%20strictly%20sex%2Dlinked%20fashion)

> THE X AND Y CHROMOSOMES
The human sex chromosomes (X and Y) originate from an ancestral homologous chromosome pair, which during mammalian evolution lost homology due to progressive degradation of the Y chromosome [[1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2435358/#R1)]. The X-chromosome in placental mammals represents approximately 5% of the haploid genome and the gene content is almost completely conserved amongst species. To ensure dosage compensation, most genes on the X are subject to X inactivation in females. The Y chromosome is much smaller than the X, being only [2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2435358/#R2)–3% of the haploid genome, and is largely composed of repeated sequences. Most genes on the Y have relatives on the X chromosome and these are not subject to X inactivation. The degeneration of the Y chromosome has been researched and reviewed extensively [2–[6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2435358/#R6)].

As a consequence, there are **no variant calls** (or SNPs) for the Y chromosome in VCF file of the Mouse Genomes Project whatsoever.

As a question: What is the reason behind wanting to use chromosome X instead of chromosome 1 for the estimation of the  genetic background? Why would you think this would give you any better results than using chr 1?

**Comment by luckysardar** [comment]
I wanted to check Hybridness in all chromosome not only X. so that I can see how much hybridness is there across the chromsome. I have seen some of the paper which have pure hybrid in some chromsome and not in other same i wanted check SNPs wise in my sample
[example](https://github.com/biocorecrg/allele_specific_RNAseq/issues/3)

**Comment by FelixKrueger** [comment]
Ah right, that makes more sense; I think reStrainingOrder is probably not the right tool for this kind of task though, because it is unlikely that different chromosomes have a completely different hybrid strain background...

I would rather suggest that you use [SNPsplit](https://github.com/FelixKrueger/SNPsplit) for a task like this. You can generate a hybrid genome with all SNPs between two strains N-masked, then index that genome and align your sample(s) of interest against it. This should then allow you to define regions of allelic imbalance on a chromosome-by-chromosome level.

**Comment by Hemantcnaik** [comment]
Okay Thanks

**Comment by luckysardar** [comment]
Okay Thanks for the suggestion
